### ISSUE TITLE
Checklist for Website Visuals

### ISSUE THREAD

**Issue by danich1** [greenelab/word-lapse#9]
This issue opens a discussion on the type of visuals needed for this website. If necessary these visuals can be open as their own issue to discuss.

- [x] A line plot that shows how a token's frequency is changing across the years
- [x] A visual or small text that depicts an actual changepoint for the token in question (no longer a line plot as I changed methods for this project)
- [x] A visual that shows a word and it's nearest neighbors together (thinking nodes and edges)
- [ ] A visual or animation that shows how a word is moving through time. (Working on generating a UMAP model for this part)

**Comment by vincerubinetti** [comment]
@danich1 and @falquaddoomi Is this list up to date? I heard you are dropping one of these. Also do I have demo json for all of this?

**Comment by danich1** [comment]
>@danich1 and @falquaddoomi Is this list up to date? I heard you are dropping one of these. Also do I have demo json for all of this?

The demo json you have should cover the first three check boxes. I'm currently working on getting the last part up for you to be able to implement.

**Comment by falquaddoomi** [comment]
@danich1 Same question about keeping this issue open as for #10 -- perhaps we move the UMAP parts to a new issue and close these out?

**Comment by danich1** [comment]
>[](https://github.com/greenelab/word-lapse/issues/9#issuecomment-1067053852)@danich1 Same question about keeping this issue open as for https://github.com/greenelab/word-lapse/issues/10 -- perhaps we move the UMAP parts to a new issue and close these out?

Feel free to close. I'll open a new issue if this feature is necessary.
